version: '2'

services:
   
  ipfs-store:
    build: ./
    image: kauri/ipfs-store
    ports:
    - "8040:8040"
    depends_on:
      - ipfs-cluster0
      - ipfs-cluster1
      - elasticsearch
    environment:
      LOG_LEVEL: TRACE
      ELASTIC_HOST: 10.5.0.15
      ELASTIC_PORT: 9300
      IPFS_HOST: 10.5.0.5
      IPFS_CLUSTER_HOST: 10.5.0.6
      IPFS_CLUSTER_PORT: 9094
      IPFS_CLUSTER_ENABLE: "true"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.16

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:6.0.0 
    ports:
          - "9200:9200"
          - "9300:9300"
    volumes:
      - .elasticsearch-docker:/data/elasticsearch
    networks:
      vpcbr:
        ipv4_address: 10.5.0.15
    
  ipfs0:
    image: jbenet/go-ipfs
    ports:
          - "4001:4001"
          - "5001:5001"
          - "8081:8080"
    volumes:
      - .ipfs0-docker-data:/data/ipfs/
      - .ipfs0-docker-staging:/export
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    
  ipfs1:
    image: jbenet/go-ipfs
    ports:
          - "4101:4001"
          - "5101:5001"
          - "8181:8080"
    volumes:
      - .ipfs1-docker-data:/data/ipfs/
      - .ipfs1-docker-staging:/export
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
              
  ipfs-cluster0:
    image: ipfs/ipfs-cluster
    depends_on:
      - ipfs0
    environment:
      CLUSTER_SECRET: 1aebe6d1ff52d96241e00d1abbd1be0743e3ccd0e3f8a05e3c8dd2bbbddb7b93
      IPFS_API: /ip4/10.5.0.5/tcp/5001
    ports:
          - "9094:9094"
          - "9095:9095"
          - "9096:9096"
    volumes:
      - .ipfs-cluster0:/data/ipfs-cluster/
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
              
  ipfs-cluster1:
    image: ipfs/ipfs-cluster
    depends_on:
      - ipfs1
      - ipfs-cluster0
    environment:
      CLUSTER_SECRET: 1aebe6d1ff52d96241e00d1abbd1be0743e3ccd0e3f8a05e3c8dd2bbbddb7b93
      IPFS_API: /ip4/10.5.0.7/tcp/5001
    ports:
          - "9194:9094"
          - "9195:9095"
          - "9196:9096"
    volumes:
      - .ipfs-cluster1:/data/ipfs-cluster/
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
      

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
