version: '2'

services:

  ipfs-store:
    build: ./
    image: kauri/ipfs-store
    ports:
    - "8040:8040"
    depends_on:
      - ipfs
      - elasticsearch
    environment:
      LOG_LEVEL: TRACE
      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: 9300
      IPFS_HOST: ipfs
    networks:
      - default

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:6.0.0 
    ports:
          - "9200:9200"
          - "9300:9300"
    volumes:
      - .elasticsearch-docker:/data/elasticsearch
    networks:
      - default
          
  ipfs:
    image: jbenet/go-ipfs
    ports:
          - "4001:4001"
          - "5001:5001"
          - "8081:8080"
    volumes:
      - .ipfs-docker-data:/data/ipfs/
      - .ipfs-docker-staging:/export

