version: '2'

services:

  ipfs-store:
    build: ./
    image: kauri/ipfs-store
    ports:
    - "8040:8040"
    depends_on:
      - ipfs
      - elasticsearch
    environment:
      LOG_LEVEL: TRACE
      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: 9300
      IPFS_HOST: ipfs
    networks:
      - default

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2 
    ports:
          - "9200:9200"
          - "9300:9300"
    volumes:
      - .elasticsearch-docker:/data/elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - default
          
  ipfs:
    image: jbenet/go-ipfs
    ports:
          - "4001:4001"
          - "5001:5001"
          - "8081:8080"
    volumes:
      - .ipfs-docker-data:/data/ipfs/
      - .ipfs-docker-staging:/export

